
CREATE TABLE ORDERING (
        id NUMBER(10) CONSTRAINT people_PK PRIMARY KEY,
        name VARCHAR2 (10) ,
        menuNum NUMBER(10) NOT NULL, 
        pay VARCHAR2(10),
        CONSTRAINT CHK_pay CHECK (pay IN ('card', 'cash')),
        CONSTRAINT FK_menuNum FOREIGN KEY (menuNum)
        REFERENCES MENUS (menuNum)
);


CREATE TABLE MENUS(
    menuNum NUMBER(10) CONSTRAINT PK_menuNum PRIMARY KEY,
    menu VARCHAR(20)  ,
    price NUMBER(10)
);

ALTER TABLE MENUS
ADD
CONSTRAINT UK_menu UNIQUE (MENU);

INSERT INTO MENUS
VALUES (1, 'PIZZA', '18000');
INSERT INTO MENUS
VALUES (2, 'HAMBURGER', '10000');
INSERT INTO MENUS
VALUES (3, 'POTATO SOUP', '5000');
INSERT INTO MENUS
VALUES (4, 'FRENCH FRIES', '3000');
INSERT INTO MENUS
VALUES (5, 'CHEESE BURGER', 13000);
INSERT INTO MENUS
VALUES (6, 'CHICKEN WING', '2000');

SELECT   *  FROM MENUS;


-- ¡÷πÆº≠
INSERT INTO ORDERING
VALUES (1, 'SMITH', 1,'card');
INSERT INTO ORDERING
VALUES (2, 'NORA', 6,'card');
INSERT INTO ORDERING
VALUES (3, 'SMITH', 3,'cash');


SELECT  * FROM ORDERING;

SELECT o.id, o.name, o.menunum, m.menu, m.price, o.pay
FROM ordering o, menus m
WHERE o.menunum = m.menunum;


DROP TABLE ORDERING
CASCADE CONSTRAINTS;